mapping.js

Adding my archive to mappings (https://hellsite.rknight.me)

Add hellsite.rknight.me to mappings

---

mapping.js

Update mapping.js to include @type__error

---

mapping.js

Adds myself to the mappings. I have used multiple usernames with this account so I have included those, but they can be removed if needed. 
Proof of my usernames (from Twitter archive SPA)

Add cutewitchphoebe

---

mapping.js

Add @lindqvistus → twitter.gustavlindqvist.se to mapping table

Add twitter.gustavlindqvist.se to mapping table

---

mapping.js

mapping: Add edwardandrews twitter account

---

mapping.js

mapping: add ZekeAranyLucas twitter account

---

mapping.js

My archives are up, so would like to map the two names to the archives. Thanks!

Mapping: Marco Zehe's Twitter accounts

---

mapping.js

https://twitter.com/ginader/ --> http://tweets.ginader.com/

mapping: added @ginader to mapping.js

---

mapping.js

Add gauntface to mapping

---

mapping.js

mapping: add @jakejarvis

---

mapping.js

Maps the twitter user @samthegeek to twarchive. Tested and ensured the LE cert works for the site.

mapping: add samthegeek

---

mapping.js

Add tweetback Twitter archive URL for @mvsde.

mapping: Add mvsde

---

mapping.js

mapping: Adding a mapping entry for rene_mobile handle to newly created archive host.

mapping: rene_mobile

---

mapping.js

mapping: add @cjtype

---

mapping.js

[@capsinthehouse](https://twitter.com/capsinthehouse) is one of our accounts. We've [decided](https://bots.reinhart1010.id/notes/98zejd7qmn) to archive this account alongside [@reinhart1010](https://twitter.com/reinhart1010) and [@alterine0101](https://twitter.com/alterine0101) - which are currently under progress.

mapping: add @capsinthehouse

---

mapping.js

I recently finished setting up my Twitter archive using tweetback, so I thought I may as well add it here. Thank you for making it!

mapping: add @santumerino

---

mapping.js

mapping: @mknepprath

---

mapping.js

Adding https://twitter.com/bandit => https://tweets.jamesn.net

mapping: add @bandit

---

mapping.js

Adding [https://twitter.com/piraces_](https://twitter.com/piraces_) => [https://tweets.piraces.dev/](https://tweets.piraces.dev/)

mapping: add @piraces_

---

mapping.js

mapping: AaronGustafson -> twitter.aaron-gustafson.com

Adding myself

---

mapping.js

mapping: add @minamarkham

---

mapping.js

Add mapping for twitter user markemer

mapping: add markemer

---

mapping.js

mapping: bmann
Canonical archives unite!

mapping: bmann

---

mapping.js

Hi 👋 
Adding my own twitter archive to the mapping. 
Thanks for making this available 🙌 
Best ^^

mapping: Add _dhar

---

mapping.js

mapping: add Robbb_J (me)

---

mapping.js

Add my (now private, no longer used) Twitter account.

mapping: Add batbeeps

---

mapping.js

mapping: add kennethson

---

mapping.js

Add mapping for @sebduggan

---

mapping.js

mapping: box464's twitter archive site is added to the file.

mapping: box464

---

mapping.js

The search box doesn't always appear, unfortunately; I don't know if that'll affect the mapping.

mapping: Add jcolag's archive

---

.gitignore
mapping.js

I'm just adding myself to the `mapping.js` file. N.B. that I think I might have messed up somewhere while serving my archive; see cooljeanius/my_tweetback_archive#1 for more info

`mapping: ` add myself

---

mapping.js

Just adding my old account to the mapping list.
Amazing tool! Have a nice day :)

mapping: Added entry to mapping list

---

mapping.js

mapping: Add @tylersticka

---

mapping.js

Thanks for the great tool! I am very happy to have archived my Twitter.
Legends!!

mapping: lorvsso -> twitter.jacklorusso.com

---

mapping.js

thanks a lot for the great project 😄 .
Adding myself (`kanekotic`) to the mapping

mapping: added kanekotic

---

mapping.js

mapping: added Julianoe

---

mapping.js

Add @HTeuMeuLeu to mapping.js.

mapping: add hteumeuleu

---

mapping.js

- Adding map for `michaelsbecker` to https://tweets.msb.fyi

mapping: add @michaelsbecker

---

mapping.js

Link to @zzamboni's Twitter archive.

mapping: Added zzamboni

---

mapping.js

mapping: Add @tomayac

---

mapping.js

mapping: Add @boogheta

---

mapping.js

mapping: add @S0lll0s

---

mapping.js

Unfortunately I have received legal threats based on the open graph images hosted in my twitter archive so I have been forced to delete it.
Which sucks as this will break my archive and others that have interacted with me, but I have no choice so have removed my name from the mapping.

mapping: removed 'accudio'
